// Copyright 2026, AsteriskBOX contributors
// SPDX-License-Identifier: GPL-3.0

package engine.root.publication

import utils.shellQuote
import utils.shellQuoteForCase

internal object RootLegacyMigrationCommand {
    fun appendGate(builder: StringBuilder, layout: RootRuntimeLayout) = with(builder) {
        val dataDir = layout.dataDir
        val legacy = listOf(
            runtimeFile(dataDir, "config-root.json"), runtimeFile(dataDir, "sing-box-root.pid"),
            runtimeFile(dataDir, "asteriskd.pid"), runtimeFile(dataDir, "asteriskd.ready"),
            runtimeFile(dataDir, "stop.sh"), runtimeFile(dataDir, "bpf-policy.json"),
            runtimeFile(dataDir, "bpf2socks.json"), runtimeFile(dataDir, "bpf2socks.pid"),
            runtimeFile(dataDir, "tun2socks.pid"), runtimeFile(dataDir, "logs/asteriskd.log"),
            RuntimeFile(layout.asteriskdStatePath),
            RuntimeFile("${layout.asteriskdStatePath}.route-localnet"),
        )
        val pidFiles = legacy.filter { it.name.endsWith(".pid") }
        val legacyTunPid = runtimeFile(dataDir, "tun2socks.pid")
        appendLine("legacy_migrate() {")
        appendLine("  if { [ -f ${layout.asteriskdConfigPath.shellQuote()} ] && grep -Eq '\"schemaVersion\"[[:space:]]*:[[:space:]]*[23]([,}])' ${layout.asteriskdConfigPath.shellQuote()}; } ||")
        appendLine("     { [ -f ${layout.asteriskdStatePath.shellQuote()} ] && grep -Eq '\"schemaVersion\"[[:space:]]*:[[:space:]]*2([,}])' ${layout.asteriskdStatePath.shellQuote()}; }; then")
        appendLine("    return 0")
        appendLine("  fi")
        appendLine("  legacy_seen=0")
        legacy.forEach { file -> appendLine("  { [ -e ${file.absolutePath.shellQuote()} ] || [ -L ${file.absolutePath.shellQuote()} ]; } && legacy_seen=1") }
        appendLine("  [ \"\$legacy_seen\" -eq 1 ] || return 0")
        appendLine("  [ -f ${layout.asteriskdConfigPath.shellQuote()} ] && [ ! -L ${layout.asteriskdConfigPath.shellQuote()} ] || return 76")
        appendLine("  grep -Eq '\"version\"[[:space:]]*:[[:space:]]*3([,}])' ${layout.asteriskdConfigPath.shellQuote()} || return 76")
        appendLine("  grep -F -q -- ${layout.asteriskdStatePath.shellQuote()} ${layout.asteriskdConfigPath.shellQuote()} || return 76")
        appendLine("  grep -F -q -- ${runtimeFile(dataDir, "stop.sh").absolutePath.shellQuote()} ${layout.asteriskdConfigPath.shellQuote()} || return 76")
        appendLine("  if [ -e ${legacyTunPid.absolutePath.shellQuote()} ]; then")
        appendLine("    grep -F -q -- ${legacyTunPid.absolutePath.shellQuote()} ${layout.asteriskdConfigPath.shellQuote()} || return 76")
        appendLine("  fi")
        appendLine("  legacy_uid=\"$(stat -c %u ${layout.dataDir.shellQuote()})\" || return 76")
        legacy.forEach { file ->
            appendLine("  if [ -e ${file.absolutePath.shellQuote()} ] || [ -L ${file.absolutePath.shellQuote()} ]; then")
            appendLine("    [ -f ${file.absolutePath.shellQuote()} ] && [ ! -L ${file.absolutePath.shellQuote()} ] || return 76")
            appendLine("    legacy_file_uid=\"$(stat -c %u ${file.absolutePath.shellQuote()})\" || return 76")
            appendLine("    [ \"\$legacy_file_uid\" = 0 ] || [ \"\$legacy_file_uid\" = \"\$legacy_uid\" ] || return 76")
            appendLine("  fi")
        }
        pidFiles.forEach { file -> appendLine("  if [ -s ${file.absolutePath.shellQuote()} ]; then grep -Eq '^[1-9][0-9]*[[:space:]]*$' ${file.absolutePath.shellQuote()} || return 76; fi") }
        appendLine("  if [ -e ${runtimeFile(dataDir, "stop.sh").absolutePath.shellQuote()} ]; then")
        appendLine("    grep -F -q -- 'Generated by AsteriskBOX' ${runtimeFile(dataDir, "stop.sh").absolutePath.shellQuote()} || return 76")
        appendLine("  fi")
        appendLine("  for legacy_proc in /proc/[0-9]*; do")
        appendLine("    [ -d \"\$legacy_proc\" ] || continue")
        appendLine("    legacy_pid=\"\${legacy_proc##*/}\"")
        appendLine("    case \"\$legacy_pid\" in")
        appendLine("      ''|*[!0-9]*) continue ;;")
        appendLine("    esac")
        appendLine("    [ \"\$legacy_pid\" = \"\$\$\" ] && continue")
        appendLine("    [ -r \"\$legacy_proc/cmdline\" ] && [ -r \"\$legacy_proc/status\" ] || return 76")
        appendLine("    legacy_cmdline=\"$(tr '\\0' ' ' < \"\$legacy_proc/cmdline\")\" || return 76")
        appendLine("    case \"\$legacy_cmdline\" in")
        appendLine("      *${runtimeFile(dataDir, "config-root.json").absolutePath.shellQuoteForCase()}*|*${layout.asteriskdConfigPath.shellQuoteForCase()}*)")
        appendLine("        legacy_uid_line=\"$(grep '^Uid:' \"\$legacy_proc/status\")\" || return 76")
        appendLine("        set -- \$legacy_uid_line")
        appendLine("        [ \"\$3\" != 0 ] && [ \"\$5\" != 0 ] || return 76")
        appendLine("        ;;")
        appendLine("    esac")
        appendLine("  done")
        legacy.forEach { file ->
            appendLine("  if [ -e ${file.absolutePath.shellQuote()} ]; then")
            appendLine("    rm -f -- ${file.absolutePath.shellQuote()} || return 76")
            appendLine("  fi")
        }
        appendLine("}")
        appendLine("legacy_migrate")
    }
}

private data class RuntimeFile(val absolutePath: String) {
    val name: String = absolutePath.substringAfterLast('/')
    val parentPath: String = absolutePath.substringBeforeLast('/')

    init {
        require(absolutePath.startsWith('/') && name.isNotEmpty() && parentPath.isNotEmpty())
    }
}

private fun runtimeFile(parent: String, child: String): RuntimeFile =
    RuntimeFile("${parent.trimEnd('/')}/${child.trimStart('/')}")
