// Copyright 2026, AsteriskBOX contributors
// SPDX-License-Identifier: GPL-3.0

package engine.root.publication

import utils.shellQuote

internal const val RootBootScriptDir = "/data/adb/service.d"
internal const val RootBootScriptPath = "$RootBootScriptDir/asteriskbox_start.sh"

internal object RootBootPublicationCommand {
    fun buildInstallation(layout: RootRuntimeLayout): String = buildString {
        appendLine("set -eu")
        appendInstallBoot(this, layout)
    }.trimEnd()

    fun buildRemoval(layout: RootRuntimeLayout): String = buildString {
        appendLine("set -eu")
        appendRemoveBoot(this, layout)
    }.trimEnd()

    internal fun appendInstallBoot(builder: StringBuilder, layout: RootRuntimeLayout) = with(builder) {
        appendLine("mkdir -p ${RootBootScriptDir.shellQuote()}")
        appendLine("mkdir -p ${layout.dataDir.shellQuote()}")
        appendLine("printf '%s' ${buildStartupScript(layout).shellQuote()} > ${layout.startupScriptPath.shellQuote()}")
        appendLine("chmod 755 ${layout.startupScriptPath.shellQuote()}")
        appendLine("printf '%s' ${buildServiceScript(layout).shellQuote()} > ${RootBootScriptPath.shellQuote()}")
        appendLine("chmod 755 ${RootBootScriptPath.shellQuote()}")
    }

    internal fun appendRemoveBoot(builder: StringBuilder, layout: RootRuntimeLayout) = with(builder) {
        appendLine("rm -f ${layout.startupScriptPath.shellQuote()} 2>/dev/null || true")
        appendLine("rm -f ${RootBootScriptPath.shellQuote()} 2>/dev/null || true")
    }

    internal fun buildStartupScript(layout: RootRuntimeLayout): String = """
        #!/system/bin/sh
        set -eu
        exec ${layout.asteriskdPath.shellQuote()} start --config ${layout.asteriskdConfigPath.shellQuote()}
    """.trimIndent() + "\n"

    internal fun buildServiceScript(layout: RootRuntimeLayout): String = """
        # Generated by AsteriskBOX. This script is executed by Magisk service.d at boot.

        (
        until [ "$(getprop sys.boot_completed)" = "1" ]; do
            sleep 1
        done
        until [ -x ${layout.startupScriptPath.shellQuote()} ]; do
            sleep 1
        done

        ${layout.startupScriptPath.shellQuote()}
        ) &
    """.trimIndent() + "\n"

}
